### PR TITLE
Avoid setState when unmounted / Fix Flow issues

### LINKED ISSUE #142: withFontLoading can call setState on unmounted components
### Type of issue

Bug

### Description

It appears that the `withFontLoading` HOC calls `this.setState` once a font loads, [here](https://github.com/fusionjs/fusion-plugin-font-loader-react/blob/master/src/with-font-loading.js#L53-L56). In the case that the component unmounts before the font loads, however, React throws some warnings for calling `setState` on an unmounted component. According to [a React blog post](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html), we should probably make the promise returned by the `font-loader` module cancellable and cancel it in `componentWillUnmount`.

### PR DESCRIPTION
**Pull request by angus-c**
Fixes #142

### CODE REVIEW

File: src/with-font-loading.js [hunk 1]
```diff
@@ -48,18 +49,23 @@ const withFontLoading = (fontName: string) => {
       }
 
       componentDidMount() {
+        this.mounted = true;
         if (this.state.$fontStyles.fontFamily !== fontName) {
-          // $FlowFixMe
+          // $FlowFixMe (this can only be browser so will not be undefined)
```
Comment (AlexMSmithCA) [inline src/with-font-loading.js]: If you did want to get rid of this, Flow's [type refinement](https://flow.org/en/docs/lang/refinements/) may help here:

```
if(loadFont) {
   loadFont(...);
}
```

Either seems reasonable to me though, given this is a limitation of Flow + isomorphic code.

Comment (angus-c) [reply src/with-font-loading.js]: I don't think that would work because the function is 

```js
export default function(font: string) {
  if (__BROWSER__ && document) {
    // $FlowFixMe
    return document.fonts && typeof document.fonts.load === 'function'
      ? document.fonts.load(`1em ${font}`) // native API requires size
      : loadFontPolyfill(font);
  }
}
```

i.e. the function is always there but if NODE it returns undefined
